import image from './images/58eb7ba7263dc-1050x656.jpg'

export const data = [
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'No Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: true,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Detenido',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: true,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Finalizado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'No Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'No Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Detenido',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Finalizado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Finalizado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
]

export const filterData = [
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: true,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: true,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: true,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
    {
        state: 'Iniciado',
        date: '03/04/21',
        people: 18,
        name: 'Nombre del proyecto',
        wishlist: false,
        address: 'Dirección del proyecto, ubicación',
        price: '2.000.030 USD',
        size: '960m2',
        progress: '81%',
        ppc: '15%',
        pcr: '46%',
        image: image
    },
]